### ISSUE TITLE
issue 2

### ISSUE THREAD

**Issue by yoonwoo0** [yoonwoo0/INFINITT_wooyoung#2]
#include <stdio.h>

int main()
{
	int N;

	printf("별 갯수 : ");
	scanf("%d", &N);

	for (int i = 0; i <= N; i++)
	{
		for (int j = N; j - i > 0; j--)
		{
			printf(" ");
		}
		for (int k = 1; k <= (i * 2) - 1; k++)
		{
			printf("%c", '*');
		}
		printf("\n");
	}

	return 0;
}

**Comment by yoonwoo0** [comment]
123

**Comment by roekdrnfl** [comment]
asdf

**Comment by roekdrnfl** [comment]
김진모
